apiVersion: batch/v1
kind: Job
metadata:
  name: init
spec:
  template:
    spec:
      containers:
      - name: init
        image: acrfabmedicalstk.azurecr.io/content-init-mel
        env:
          - name: MONGODB_CONNECTION
            valueFrom:
              secretKeyRef:
                name: cosmosdb
                key: db
      restartPolicy: Never
  backoffLimit: 4